name: flake8

on:
  push:
    paths:
    - 'server/**.py'
  
  pull_request:
    paths:
    - 'server/**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    env:
      working-directory: "./server"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
      working-directory: ${{ env.working-directory }}
    - name: Lint with flake8
      run: |
        pipenv run flake8
      working-directory: ${{ env.working-directory }}
